In [1]:
import torch
import torch.nn as nn

def CausalConv1d(in_channels, out_channels, kernel_size, dilation=1, **kwargs):
   pad = (kernel_size - 1) * dilation
   return nn.Conv1d(in_channels, out_channels, kernel_size, padding=pad, dilation=dilation, **kwargs)

In [2]:
m = CausalConv1d(1, 1, kernel_size=3, dilation=2, bias=False)
x = torch.autograd.Variable(torch.randn(1, 1, 9))
x[:, :, :3].data.zero_()
print(x)
print(m(x)) 

tensor([[[ 0.0000,  0.0000,  0.0000, -1.7409, -0.7757,  0.0357,  0.5658,
          -1.2035, -1.0776]]])
tensor([[[ 0.0000,  0.0000,  0.0000, -0.6362, -0.2835,  0.6985,  0.5122,
          -0.6059, -0.6843,  0.4770,  0.4737, -0.1051, -0.0941]]],
       grad_fn=<SqueezeBackward1>)


In [12]:
class Network(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = CausalConv1d(1, 1, kernel_size=3, dilation=1)

    def forward(self, x):
        x = self.conv1(x)
        #         x = x[:, :, :-self.conv1.padding[0]]  # remove trailing padding
        return x

In [13]:
net=Network()
x = torch.randn(1, 1, 9)
x[:, :, :3].data.zero_()
print(x)
print(net(x))

tensor([[[ 0.0000,  0.0000,  0.0000,  1.3245, -0.2668, -0.3200, -0.7043,
           1.3234,  1.1346]]])


RuntimeError: dilation should be greater than zero, but got [1, 0]