In [14]:
import torch
import torch.nn as nn

def CausalConv1d(in_channels, out_channels, kernel_size, dilation=1, **kwargs):
   pad = (kernel_size - 1) * dilation
   return nn.Conv1d(in_channels, out_channels, kernel_size, padding=pad, dilation=dilation, **kwargs)

In [15]:
m = CausalConv1d(1, 1, kernel_size=3, dilation=2, bias=False)
x = torch.autograd.Variable(torch.randn(1, 1, 9))
x[:, :, :3].data.zero_()
print(x)
print(m(x)) 

tensor([[[ 0.0000,  0.0000,  0.0000,  1.4287, -0.2283,  0.9576, -1.3580,
          -1.4830,  0.9825]]])
tensor([[[ 0.0000,  0.0000,  0.0000, -0.0649,  0.0104, -0.7645,  0.1769,
          -0.0987,  0.5900,  0.9611, -0.7974, -0.3293,  0.2182]]],
       grad_fn=<SqueezeBackward1>)


In [16]:
class Network(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = CausalConv1d(1, 1, kernel_size=3, dilation=1)

    def forward(self, x):
        x = self.conv1(x)
        #         x = x[:, :, :-self.conv1.padding[0]]  # remove trailing padding
        return x

In [17]:
net=Network()
x = torch.randn(1, 1, 9)
x[:, :, :3].data.zero_()
print(x)
print(net(x).shape)

tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  3.4293e-01,  5.9516e-01,
           5.4752e-04, -5.8277e-01,  4.6650e-01,  7.9391e-01]]])
torch.Size([1, 1, 11])
